/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJsonQScopeProvider extends DelegatingScopeProvider {
}
