/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.jsonQ;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Additional Query</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.course.jsonQ.AdditionalQuery#getConnector <em>Connector</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.AdditionalQuery#getQ2key <em>Q2key</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.AdditionalQuery#getQ2val <em>Q2val</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getAdditionalQuery()
 * @model
 * @generated
 */
public interface AdditionalQuery extends EObject
{
  /**
   * Returns the value of the '<em><b>Connector</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connector</em>' attribute.
   * @see #setConnector(String)
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getAdditionalQuery_Connector()
   * @model
   * @generated
   */
  String getConnector();

  /**
   * Sets the value of the '{@link uk.ac.kcl.course.jsonQ.AdditionalQuery#getConnector <em>Connector</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Connector</em>' attribute.
   * @see #getConnector()
   * @generated
   */
  void setConnector(String value);

  /**
   * Returns the value of the '<em><b>Q2key</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.course.jsonQ.InputFieldSingle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Q2key</em>' attribute.
   * @see uk.ac.kcl.course.jsonQ.InputFieldSingle
   * @see #setQ2key(InputFieldSingle)
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getAdditionalQuery_Q2key()
   * @model
   * @generated
   */
  InputFieldSingle getQ2key();

  /**
   * Sets the value of the '{@link uk.ac.kcl.course.jsonQ.AdditionalQuery#getQ2key <em>Q2key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Q2key</em>' attribute.
   * @see uk.ac.kcl.course.jsonQ.InputFieldSingle
   * @see #getQ2key()
   * @generated
   */
  void setQ2key(InputFieldSingle value);

  /**
   * Returns the value of the '<em><b>Q2val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Q2val</em>' containment reference.
   * @see #setQ2val(InputVal)
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getAdditionalQuery_Q2val()
   * @model containment="true"
   * @generated
   */
  InputVal getQ2val();

  /**
   * Sets the value of the '{@link uk.ac.kcl.course.jsonQ.AdditionalQuery#getQ2val <em>Q2val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Q2val</em>' containment reference.
   * @see #getQ2val()
   * @generated
   */
  void setQ2val(InputVal value);

} // AdditionalQuery
