/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.jsonQ;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Get Statements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.course.jsonQ.GetStatements#getOpGet <em>Op Get</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getGetStatements()
 * @model
 * @generated
 */
public interface GetStatements extends Statements
{
  /**
   * Returns the value of the '<em><b>Op Get</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.course.jsonQ.OperationGET}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op Get</em>' attribute.
   * @see uk.ac.kcl.course.jsonQ.OperationGET
   * @see #setOpGet(OperationGET)
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getGetStatements_OpGet()
   * @model
   * @generated
   */
  OperationGET getOpGet();

  /**
   * Sets the value of the '{@link uk.ac.kcl.course.jsonQ.GetStatements#getOpGet <em>Op Get</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op Get</em>' attribute.
   * @see uk.ac.kcl.course.jsonQ.OperationGET
   * @see #getOpGet()
   * @generated
   */
  void setOpGet(OperationGET value);

} // GetStatements
