/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.jsonQ;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Val</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getInputVal()
 * @model
 * @generated
 */
public interface InputVal extends EObject
{
} // InputVal
