/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.jsonQ;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Input Field Single</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getInputFieldSingle()
 * @model
 * @generated
 */
public enum InputFieldSingle implements Enumerator
{
  /**
   * The '<em><b>Area Type</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AREA_TYPE_VALUE
   * @generated
   * @ordered
   */
  AREA_TYPE(0, "areaType", "areaType"),

  /**
   * The '<em><b>Area Name</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AREA_NAME_VALUE
   * @generated
   * @ordered
   */
  AREA_NAME(1, "areaName", "areaName"),

  /**
   * The '<em><b>Area Code</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AREA_CODE_VALUE
   * @generated
   * @ordered
   */
  AREA_CODE(2, "areaCode", "areaCode");

  /**
   * The '<em><b>Area Type</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AREA_TYPE
   * @model name="areaType"
   * @generated
   * @ordered
   */
  public static final int AREA_TYPE_VALUE = 0;

  /**
   * The '<em><b>Area Name</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AREA_NAME
   * @model name="areaName"
   * @generated
   * @ordered
   */
  public static final int AREA_NAME_VALUE = 1;

  /**
   * The '<em><b>Area Code</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AREA_CODE
   * @model name="areaCode"
   * @generated
   * @ordered
   */
  public static final int AREA_CODE_VALUE = 2;

  /**
   * An array of all the '<em><b>Input Field Single</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final InputFieldSingle[] VALUES_ARRAY =
    new InputFieldSingle[]
    {
      AREA_TYPE,
      AREA_NAME,
      AREA_CODE,
    };

  /**
   * A public read-only list of all the '<em><b>Input Field Single</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<InputFieldSingle> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Input Field Single</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static InputFieldSingle get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      InputFieldSingle result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Input Field Single</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static InputFieldSingle getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      InputFieldSingle result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Input Field Single</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static InputFieldSingle get(int value)
  {
    switch (value)
    {
      case AREA_TYPE_VALUE: return AREA_TYPE;
      case AREA_NAME_VALUE: return AREA_NAME;
      case AREA_CODE_VALUE: return AREA_CODE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private InputFieldSingle(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //InputFieldSingle
