/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.jsonQ;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.course.jsonQ.JsonQFactory
 * @model kind="package"
 * @generated
 */
public interface JsonQPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "jsonQ";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/course/JsonQ";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "jsonQ";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JsonQPackage eINSTANCE = uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.course.jsonQ.impl.JSONQueryModelImpl <em>JSON Query Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.course.jsonQ.impl.JSONQueryModelImpl
   * @see uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl#getJSONQueryModel()
   * @generated
   */
  int JSON_QUERY_MODEL = 0;

  /**
   * The feature id for the '<em><b>Input Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_QUERY_MODEL__INPUT_STATEMENT = 0;

  /**
   * The number of structural features of the '<em>JSON Query Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JSON_QUERY_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.course.jsonQ.impl.StatementsImpl <em>Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.course.jsonQ.impl.StatementsImpl
   * @see uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl#getStatements()
   * @generated
   */
  int STATEMENTS = 1;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS__OPERATION = 0;

  /**
   * The feature id for the '<em><b>Q1key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS__Q1KEY = 1;

  /**
   * The feature id for the '<em><b>Q1val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS__Q1VAL = 2;

  /**
   * The feature id for the '<em><b>Connector</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS__CONNECTOR = 3;

  /**
   * The feature id for the '<em><b>Q2key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS__Q2KEY = 4;

  /**
   * The feature id for the '<em><b>Q2val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS__Q2VAL = 5;

  /**
   * The number of structural features of the '<em>Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link uk.ac.kcl.course.jsonQ.impl.InputValImpl <em>Input Val</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.course.jsonQ.impl.InputValImpl
   * @see uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl#getInputVal()
   * @generated
   */
  int INPUT_VAL = 2;

  /**
   * The number of structural features of the '<em>Input Val</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_VAL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.course.jsonQ.impl.StringLiteralImpl <em>String Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.course.jsonQ.impl.StringLiteralImpl
   * @see uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl#getStringLiteral()
   * @generated
   */
  int STRING_LITERAL = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL__VALUE = INPUT_VAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL_FEATURE_COUNT = INPUT_VAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.course.jsonQ.impl.INTLiteralImpl <em>INT Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.course.jsonQ.impl.INTLiteralImpl
   * @see uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl#getINTLiteral()
   * @generated
   */
  int INT_LITERAL = 4;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VALUE = INPUT_VAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>INT Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = INPUT_VAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.course.jsonQ.Operation <em>Operation</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.course.jsonQ.Operation
   * @see uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 5;

  /**
   * The meta object id for the '{@link uk.ac.kcl.course.jsonQ.InputFieldSingle <em>Input Field Single</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.course.jsonQ.InputFieldSingle
   * @see uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl#getInputFieldSingle()
   * @generated
   */
  int INPUT_FIELD_SINGLE = 6;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.course.jsonQ.JSONQueryModel <em>JSON Query Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JSON Query Model</em>'.
   * @see uk.ac.kcl.course.jsonQ.JSONQueryModel
   * @generated
   */
  EClass getJSONQueryModel();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.course.jsonQ.JSONQueryModel#getInputStatement <em>Input Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Input Statement</em>'.
   * @see uk.ac.kcl.course.jsonQ.JSONQueryModel#getInputStatement()
   * @see #getJSONQueryModel()
   * @generated
   */
  EReference getJSONQueryModel_InputStatement();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.course.jsonQ.Statements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statements</em>'.
   * @see uk.ac.kcl.course.jsonQ.Statements
   * @generated
   */
  EClass getStatements();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.course.jsonQ.Statements#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see uk.ac.kcl.course.jsonQ.Statements#getOperation()
   * @see #getStatements()
   * @generated
   */
  EAttribute getStatements_Operation();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.course.jsonQ.Statements#getQ1key <em>Q1key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Q1key</em>'.
   * @see uk.ac.kcl.course.jsonQ.Statements#getQ1key()
   * @see #getStatements()
   * @generated
   */
  EAttribute getStatements_Q1key();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.course.jsonQ.Statements#getQ1val <em>Q1val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Q1val</em>'.
   * @see uk.ac.kcl.course.jsonQ.Statements#getQ1val()
   * @see #getStatements()
   * @generated
   */
  EReference getStatements_Q1val();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.course.jsonQ.Statements#getConnector <em>Connector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Connector</em>'.
   * @see uk.ac.kcl.course.jsonQ.Statements#getConnector()
   * @see #getStatements()
   * @generated
   */
  EAttribute getStatements_Connector();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.course.jsonQ.Statements#getQ2key <em>Q2key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Q2key</em>'.
   * @see uk.ac.kcl.course.jsonQ.Statements#getQ2key()
   * @see #getStatements()
   * @generated
   */
  EAttribute getStatements_Q2key();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.course.jsonQ.Statements#getQ2val <em>Q2val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Q2val</em>'.
   * @see uk.ac.kcl.course.jsonQ.Statements#getQ2val()
   * @see #getStatements()
   * @generated
   */
  EReference getStatements_Q2val();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.course.jsonQ.InputVal <em>Input Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input Val</em>'.
   * @see uk.ac.kcl.course.jsonQ.InputVal
   * @generated
   */
  EClass getInputVal();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.course.jsonQ.StringLiteral <em>String Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Literal</em>'.
   * @see uk.ac.kcl.course.jsonQ.StringLiteral
   * @generated
   */
  EClass getStringLiteral();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.course.jsonQ.StringLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.course.jsonQ.StringLiteral#getValue()
   * @see #getStringLiteral()
   * @generated
   */
  EAttribute getStringLiteral_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.course.jsonQ.INTLiteral <em>INT Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>INT Literal</em>'.
   * @see uk.ac.kcl.course.jsonQ.INTLiteral
   * @generated
   */
  EClass getINTLiteral();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.course.jsonQ.INTLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.course.jsonQ.INTLiteral#getValue()
   * @see #getINTLiteral()
   * @generated
   */
  EAttribute getINTLiteral_Value();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.course.jsonQ.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Operation</em>'.
   * @see uk.ac.kcl.course.jsonQ.Operation
   * @generated
   */
  EEnum getOperation();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.course.jsonQ.InputFieldSingle <em>Input Field Single</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Input Field Single</em>'.
   * @see uk.ac.kcl.course.jsonQ.InputFieldSingle
   * @generated
   */
  EEnum getInputFieldSingle();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JsonQFactory getJsonQFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.course.jsonQ.impl.JSONQueryModelImpl <em>JSON Query Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.course.jsonQ.impl.JSONQueryModelImpl
     * @see uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl#getJSONQueryModel()
     * @generated
     */
    EClass JSON_QUERY_MODEL = eINSTANCE.getJSONQueryModel();

    /**
     * The meta object literal for the '<em><b>Input Statement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JSON_QUERY_MODEL__INPUT_STATEMENT = eINSTANCE.getJSONQueryModel_InputStatement();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.course.jsonQ.impl.StatementsImpl <em>Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.course.jsonQ.impl.StatementsImpl
     * @see uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl#getStatements()
     * @generated
     */
    EClass STATEMENTS = eINSTANCE.getStatements();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENTS__OPERATION = eINSTANCE.getStatements_Operation();

    /**
     * The meta object literal for the '<em><b>Q1key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENTS__Q1KEY = eINSTANCE.getStatements_Q1key();

    /**
     * The meta object literal for the '<em><b>Q1val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENTS__Q1VAL = eINSTANCE.getStatements_Q1val();

    /**
     * The meta object literal for the '<em><b>Connector</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENTS__CONNECTOR = eINSTANCE.getStatements_Connector();

    /**
     * The meta object literal for the '<em><b>Q2key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENTS__Q2KEY = eINSTANCE.getStatements_Q2key();

    /**
     * The meta object literal for the '<em><b>Q2val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENTS__Q2VAL = eINSTANCE.getStatements_Q2val();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.course.jsonQ.impl.InputValImpl <em>Input Val</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.course.jsonQ.impl.InputValImpl
     * @see uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl#getInputVal()
     * @generated
     */
    EClass INPUT_VAL = eINSTANCE.getInputVal();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.course.jsonQ.impl.StringLiteralImpl <em>String Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.course.jsonQ.impl.StringLiteralImpl
     * @see uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl#getStringLiteral()
     * @generated
     */
    EClass STRING_LITERAL = eINSTANCE.getStringLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_LITERAL__VALUE = eINSTANCE.getStringLiteral_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.course.jsonQ.impl.INTLiteralImpl <em>INT Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.course.jsonQ.impl.INTLiteralImpl
     * @see uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl#getINTLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getINTLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VALUE = eINSTANCE.getINTLiteral_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.course.jsonQ.Operation <em>Operation</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.course.jsonQ.Operation
     * @see uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl#getOperation()
     * @generated
     */
    EEnum OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.course.jsonQ.InputFieldSingle <em>Input Field Single</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.course.jsonQ.InputFieldSingle
     * @see uk.ac.kcl.course.jsonQ.impl.JsonQPackageImpl#getInputFieldSingle()
     * @generated
     */
    EEnum INPUT_FIELD_SINGLE = eINSTANCE.getInputFieldSingle();

  }

} //JsonQPackage
