/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.jsonQ;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JSON Query Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.course.jsonQ.JSONQueryModel#getInputStatement <em>Input Statement</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getJSONQueryModel()
 * @model
 * @generated
 */
public interface JSONQueryModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Input Statement</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.course.jsonQ.Statements}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Statement</em>' containment reference list.
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getJSONQueryModel_InputStatement()
   * @model containment="true"
   * @generated
   */
  EList<Statements> getInputStatement();

} // JSONQueryModel
