/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.jsonQ;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.course.jsonQ.Statements#getQ1key <em>Q1key</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.Statements#getQ1val <em>Q1val</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.Statements#getQryadditional <em>Qryadditional</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getStatements()
 * @model
 * @generated
 */
public interface Statements extends EObject
{
  /**
   * Returns the value of the '<em><b>Q1key</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.course.jsonQ.InputFieldSingle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Q1key</em>' attribute.
   * @see uk.ac.kcl.course.jsonQ.InputFieldSingle
   * @see #setQ1key(InputFieldSingle)
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getStatements_Q1key()
   * @model
   * @generated
   */
  InputFieldSingle getQ1key();

  /**
   * Sets the value of the '{@link uk.ac.kcl.course.jsonQ.Statements#getQ1key <em>Q1key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Q1key</em>' attribute.
   * @see uk.ac.kcl.course.jsonQ.InputFieldSingle
   * @see #getQ1key()
   * @generated
   */
  void setQ1key(InputFieldSingle value);

  /**
   * Returns the value of the '<em><b>Q1val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Q1val</em>' containment reference.
   * @see #setQ1val(InputVal)
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getStatements_Q1val()
   * @model containment="true"
   * @generated
   */
  InputVal getQ1val();

  /**
   * Sets the value of the '{@link uk.ac.kcl.course.jsonQ.Statements#getQ1val <em>Q1val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Q1val</em>' containment reference.
   * @see #getQ1val()
   * @generated
   */
  void setQ1val(InputVal value);

  /**
   * Returns the value of the '<em><b>Qryadditional</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qryadditional</em>' containment reference.
   * @see #setQryadditional(AdditionalQuery)
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getStatements_Qryadditional()
   * @model containment="true"
   * @generated
   */
  AdditionalQuery getQryadditional();

  /**
   * Sets the value of the '{@link uk.ac.kcl.course.jsonQ.Statements#getQryadditional <em>Qryadditional</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qryadditional</em>' containment reference.
   * @see #getQryadditional()
   * @generated
   */
  void setQryadditional(AdditionalQuery value);

} // Statements
