/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.jsonQ;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.course.jsonQ.Statements#getOperation <em>Operation</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.Statements#getQ1key <em>Q1key</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.Statements#getQ1val <em>Q1val</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.Statements#getConnector <em>Connector</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.Statements#getQ2key <em>Q2key</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.Statements#getQ2val <em>Q2val</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getStatements()
 * @model
 * @generated
 */
public interface Statements extends EObject
{
  /**
   * Returns the value of the '<em><b>Operation</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.course.jsonQ.Operation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' attribute.
   * @see uk.ac.kcl.course.jsonQ.Operation
   * @see #setOperation(Operation)
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getStatements_Operation()
   * @model
   * @generated
   */
  Operation getOperation();

  /**
   * Sets the value of the '{@link uk.ac.kcl.course.jsonQ.Statements#getOperation <em>Operation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' attribute.
   * @see uk.ac.kcl.course.jsonQ.Operation
   * @see #getOperation()
   * @generated
   */
  void setOperation(Operation value);

  /**
   * Returns the value of the '<em><b>Q1key</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.course.jsonQ.InputFieldSingle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Q1key</em>' attribute.
   * @see uk.ac.kcl.course.jsonQ.InputFieldSingle
   * @see #setQ1key(InputFieldSingle)
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getStatements_Q1key()
   * @model
   * @generated
   */
  InputFieldSingle getQ1key();

  /**
   * Sets the value of the '{@link uk.ac.kcl.course.jsonQ.Statements#getQ1key <em>Q1key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Q1key</em>' attribute.
   * @see uk.ac.kcl.course.jsonQ.InputFieldSingle
   * @see #getQ1key()
   * @generated
   */
  void setQ1key(InputFieldSingle value);

  /**
   * Returns the value of the '<em><b>Q1val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Q1val</em>' containment reference.
   * @see #setQ1val(InputVal)
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getStatements_Q1val()
   * @model containment="true"
   * @generated
   */
  InputVal getQ1val();

  /**
   * Sets the value of the '{@link uk.ac.kcl.course.jsonQ.Statements#getQ1val <em>Q1val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Q1val</em>' containment reference.
   * @see #getQ1val()
   * @generated
   */
  void setQ1val(InputVal value);

  /**
   * Returns the value of the '<em><b>Connector</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connector</em>' attribute list.
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getStatements_Connector()
   * @model unique="false"
   * @generated
   */
  EList<String> getConnector();

  /**
   * Returns the value of the '<em><b>Q2key</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.course.jsonQ.InputFieldSingle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Q2key</em>' attribute.
   * @see uk.ac.kcl.course.jsonQ.InputFieldSingle
   * @see #setQ2key(InputFieldSingle)
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getStatements_Q2key()
   * @model
   * @generated
   */
  InputFieldSingle getQ2key();

  /**
   * Sets the value of the '{@link uk.ac.kcl.course.jsonQ.Statements#getQ2key <em>Q2key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Q2key</em>' attribute.
   * @see uk.ac.kcl.course.jsonQ.InputFieldSingle
   * @see #getQ2key()
   * @generated
   */
  void setQ2key(InputFieldSingle value);

  /**
   * Returns the value of the '<em><b>Q2val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Q2val</em>' containment reference.
   * @see #setQ2val(InputVal)
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#getStatements_Q2val()
   * @model containment="true"
   * @generated
   */
  InputVal getQ2val();

  /**
   * Sets the value of the '{@link uk.ac.kcl.course.jsonQ.Statements#getQ2val <em>Q2val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Q2val</em>' containment reference.
   * @see #getQ2val()
   * @generated
   */
  void setQ2val(InputVal value);

} // Statements
