/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import uk.ac.kcl.course.ide.contentassist.antlr.internal.InternalJsonQParser;
import uk.ac.kcl.course.services.JsonQGrammarAccess;

public class JsonQParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(JsonQGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, JsonQGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStatementsAccess().getConnectorAlternatives_5_0(), "rule__Statements__ConnectorAlternatives_5_0");
			builder.put(grammarAccess.getInputValAccess().getAlternatives(), "rule__InputVal__Alternatives");
			builder.put(grammarAccess.getInputFieldSingleAccess().getAlternatives(), "rule__InputFieldSingle__Alternatives");
			builder.put(grammarAccess.getStatementsAccess().getGroup(), "rule__Statements__Group__0");
			builder.put(grammarAccess.getStatementsAccess().getGroup_6(), "rule__Statements__Group_6__0");
			builder.put(grammarAccess.getJSONQueryModelAccess().getInputStatementAssignment(), "rule__JSONQueryModel__InputStatementAssignment");
			builder.put(grammarAccess.getStatementsAccess().getOperationAssignment_1(), "rule__Statements__OperationAssignment_1");
			builder.put(grammarAccess.getStatementsAccess().getQ1keyAssignment_3(), "rule__Statements__Q1keyAssignment_3");
			builder.put(grammarAccess.getStatementsAccess().getQ1valAssignment_4(), "rule__Statements__Q1valAssignment_4");
			builder.put(grammarAccess.getStatementsAccess().getConnectorAssignment_5(), "rule__Statements__ConnectorAssignment_5");
			builder.put(grammarAccess.getStatementsAccess().getQ2keyAssignment_6_0(), "rule__Statements__Q2keyAssignment_6_0");
			builder.put(grammarAccess.getStatementsAccess().getQ2valAssignment_6_1(), "rule__Statements__Q2valAssignment_6_1");
			builder.put(grammarAccess.getStringLiteralAccess().getValueAssignment(), "rule__StringLiteral__ValueAssignment");
			builder.put(grammarAccess.getINTLiteralAccess().getValueAssignment(), "rule__INTLiteral__ValueAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private JsonQGrammarAccess grammarAccess;

	@Override
	protected InternalJsonQParser createParser() {
		InternalJsonQParser result = new InternalJsonQParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public JsonQGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JsonQGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
