/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.jsonQ.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.ac.kcl.course.jsonQ.AggregateStatements;
import uk.ac.kcl.course.jsonQ.InputFieldSingle;
import uk.ac.kcl.course.jsonQ.JsonQPackage;
import uk.ac.kcl.course.jsonQ.OperationAgg;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Aggregate Statements</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.course.jsonQ.impl.AggregateStatementsImpl#getOpAgg <em>Op Agg</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.impl.AggregateStatementsImpl#getAggField <em>Agg Field</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AggregateStatementsImpl extends StatementsImpl implements AggregateStatements
{
  /**
   * The default value of the '{@link #getOpAgg() <em>Op Agg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpAgg()
   * @generated
   * @ordered
   */
  protected static final OperationAgg OP_AGG_EDEFAULT = OperationAgg.AVG;

  /**
   * The cached value of the '{@link #getOpAgg() <em>Op Agg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpAgg()
   * @generated
   * @ordered
   */
  protected OperationAgg opAgg = OP_AGG_EDEFAULT;

  /**
   * The default value of the '{@link #getAggField() <em>Agg Field</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAggField()
   * @generated
   * @ordered
   */
  protected static final InputFieldSingle AGG_FIELD_EDEFAULT = InputFieldSingle.FIRST_NAME;

  /**
   * The cached value of the '{@link #getAggField() <em>Agg Field</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAggField()
   * @generated
   * @ordered
   */
  protected InputFieldSingle aggField = AGG_FIELD_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AggregateStatementsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonQPackage.Literals.AGGREGATE_STATEMENTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationAgg getOpAgg()
  {
    return opAgg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOpAgg(OperationAgg newOpAgg)
  {
    OperationAgg oldOpAgg = opAgg;
    opAgg = newOpAgg == null ? OP_AGG_EDEFAULT : newOpAgg;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonQPackage.AGGREGATE_STATEMENTS__OP_AGG, oldOpAgg, opAgg));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InputFieldSingle getAggField()
  {
    return aggField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAggField(InputFieldSingle newAggField)
  {
    InputFieldSingle oldAggField = aggField;
    aggField = newAggField == null ? AGG_FIELD_EDEFAULT : newAggField;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonQPackage.AGGREGATE_STATEMENTS__AGG_FIELD, oldAggField, aggField));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JsonQPackage.AGGREGATE_STATEMENTS__OP_AGG:
        return getOpAgg();
      case JsonQPackage.AGGREGATE_STATEMENTS__AGG_FIELD:
        return getAggField();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JsonQPackage.AGGREGATE_STATEMENTS__OP_AGG:
        setOpAgg((OperationAgg)newValue);
        return;
      case JsonQPackage.AGGREGATE_STATEMENTS__AGG_FIELD:
        setAggField((InputFieldSingle)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JsonQPackage.AGGREGATE_STATEMENTS__OP_AGG:
        setOpAgg(OP_AGG_EDEFAULT);
        return;
      case JsonQPackage.AGGREGATE_STATEMENTS__AGG_FIELD:
        setAggField(AGG_FIELD_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JsonQPackage.AGGREGATE_STATEMENTS__OP_AGG:
        return opAgg != OP_AGG_EDEFAULT;
      case JsonQPackage.AGGREGATE_STATEMENTS__AGG_FIELD:
        return aggField != AGG_FIELD_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (opAgg: ");
    result.append(opAgg);
    result.append(", aggField: ");
    result.append(aggField);
    result.append(')');
    return result.toString();
  }

} //AggregateStatementsImpl
