/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.jsonQ.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.ac.kcl.course.jsonQ.GetStatements;
import uk.ac.kcl.course.jsonQ.JsonQPackage;
import uk.ac.kcl.course.jsonQ.OperationGET;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Get Statements</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.course.jsonQ.impl.GetStatementsImpl#getOpGet <em>Op Get</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GetStatementsImpl extends StatementsImpl implements GetStatements
{
  /**
   * The default value of the '{@link #getOpGet() <em>Op Get</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpGet()
   * @generated
   * @ordered
   */
  protected static final OperationGET OP_GET_EDEFAULT = OperationGET.DATA;

  /**
   * The cached value of the '{@link #getOpGet() <em>Op Get</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpGet()
   * @generated
   * @ordered
   */
  protected OperationGET opGet = OP_GET_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GetStatementsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonQPackage.Literals.GET_STATEMENTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationGET getOpGet()
  {
    return opGet;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOpGet(OperationGET newOpGet)
  {
    OperationGET oldOpGet = opGet;
    opGet = newOpGet == null ? OP_GET_EDEFAULT : newOpGet;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonQPackage.GET_STATEMENTS__OP_GET, oldOpGet, opGet));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JsonQPackage.GET_STATEMENTS__OP_GET:
        return getOpGet();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JsonQPackage.GET_STATEMENTS__OP_GET:
        setOpGet((OperationGET)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JsonQPackage.GET_STATEMENTS__OP_GET:
        setOpGet(OP_GET_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JsonQPackage.GET_STATEMENTS__OP_GET:
        return opGet != OP_GET_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (opGet: ");
    result.append(opGet);
    result.append(')');
    return result.toString();
  }

} //GetStatementsImpl
