/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.jsonQ.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uk.ac.kcl.course.jsonQ.JSONQueryModel;
import uk.ac.kcl.course.jsonQ.JsonQPackage;
import uk.ac.kcl.course.jsonQ.Statements;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>JSON Query Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.course.jsonQ.impl.JSONQueryModelImpl#getInputStatement <em>Input Statement</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JSONQueryModelImpl extends MinimalEObjectImpl.Container implements JSONQueryModel
{
  /**
   * The cached value of the '{@link #getInputStatement() <em>Input Statement</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInputStatement()
   * @generated
   * @ordered
   */
  protected EList<Statements> inputStatement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JSONQueryModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonQPackage.Literals.JSON_QUERY_MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Statements> getInputStatement()
  {
    if (inputStatement == null)
    {
      inputStatement = new EObjectContainmentEList<Statements>(Statements.class, this, JsonQPackage.JSON_QUERY_MODEL__INPUT_STATEMENT);
    }
    return inputStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JsonQPackage.JSON_QUERY_MODEL__INPUT_STATEMENT:
        return ((InternalEList<?>)getInputStatement()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JsonQPackage.JSON_QUERY_MODEL__INPUT_STATEMENT:
        return getInputStatement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JsonQPackage.JSON_QUERY_MODEL__INPUT_STATEMENT:
        getInputStatement().clear();
        getInputStatement().addAll((Collection<? extends Statements>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JsonQPackage.JSON_QUERY_MODEL__INPUT_STATEMENT:
        getInputStatement().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JsonQPackage.JSON_QUERY_MODEL__INPUT_STATEMENT:
        return inputStatement != null && !inputStatement.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //JSONQueryModelImpl
