/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.jsonQ.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import uk.ac.kcl.course.jsonQ.AdditionalQuery;
import uk.ac.kcl.course.jsonQ.AggregateStatements;
import uk.ac.kcl.course.jsonQ.Connector;
import uk.ac.kcl.course.jsonQ.GetStatements;
import uk.ac.kcl.course.jsonQ.INTLiteral;
import uk.ac.kcl.course.jsonQ.InputFieldSingle;
import uk.ac.kcl.course.jsonQ.InputVal;
import uk.ac.kcl.course.jsonQ.JSONQueryModel;
import uk.ac.kcl.course.jsonQ.JsonQFactory;
import uk.ac.kcl.course.jsonQ.JsonQPackage;
import uk.ac.kcl.course.jsonQ.OperationAgg;
import uk.ac.kcl.course.jsonQ.OperationGET;
import uk.ac.kcl.course.jsonQ.Statements;
import uk.ac.kcl.course.jsonQ.StringLiteral;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class JsonQPackageImpl extends EPackageImpl implements JsonQPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jsonQueryModelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass statementsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass aggregateStatementsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass getStatementsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass additionalQueryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass inputValEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass intLiteralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stringLiteralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum connectorEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum operationAggEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum operationGETEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum inputFieldSingleEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see uk.ac.kcl.course.jsonQ.JsonQPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private JsonQPackageImpl()
  {
    super(eNS_URI, JsonQFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link JsonQPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static JsonQPackage init()
  {
    if (isInited) return (JsonQPackage)EPackage.Registry.INSTANCE.getEPackage(JsonQPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredJsonQPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    JsonQPackageImpl theJsonQPackage = registeredJsonQPackage instanceof JsonQPackageImpl ? (JsonQPackageImpl)registeredJsonQPackage : new JsonQPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theJsonQPackage.createPackageContents();

    // Initialize created meta-data
    theJsonQPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theJsonQPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(JsonQPackage.eNS_URI, theJsonQPackage);
    return theJsonQPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJSONQueryModel()
  {
    return jsonQueryModelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJSONQueryModel_InputStatement()
  {
    return (EReference)jsonQueryModelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStatements()
  {
    return statementsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStatements_Q1key()
  {
    return (EAttribute)statementsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStatements_Q1val()
  {
    return (EReference)statementsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStatements_Qryadditional()
  {
    return (EReference)statementsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAggregateStatements()
  {
    return aggregateStatementsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAggregateStatements_OpAgg()
  {
    return (EAttribute)aggregateStatementsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAggregateStatements_AggField()
  {
    return (EAttribute)aggregateStatementsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGetStatements()
  {
    return getStatementsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGetStatements_OpGet()
  {
    return (EAttribute)getStatementsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAdditionalQuery()
  {
    return additionalQueryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAdditionalQuery_Connector()
  {
    return (EAttribute)additionalQueryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAdditionalQuery_Q2key()
  {
    return (EAttribute)additionalQueryEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAdditionalQuery_Q2val()
  {
    return (EReference)additionalQueryEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInputVal()
  {
    return inputValEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getINTLiteral()
  {
    return intLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getINTLiteral_Value()
  {
    return (EAttribute)intLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStringLiteral()
  {
    return stringLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStringLiteral_Value()
  {
    return (EAttribute)stringLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getConnector()
  {
    return connectorEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getOperationAgg()
  {
    return operationAggEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getOperationGET()
  {
    return operationGETEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getInputFieldSingle()
  {
    return inputFieldSingleEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsonQFactory getJsonQFactory()
  {
    return (JsonQFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    jsonQueryModelEClass = createEClass(JSON_QUERY_MODEL);
    createEReference(jsonQueryModelEClass, JSON_QUERY_MODEL__INPUT_STATEMENT);

    statementsEClass = createEClass(STATEMENTS);
    createEAttribute(statementsEClass, STATEMENTS__Q1KEY);
    createEReference(statementsEClass, STATEMENTS__Q1VAL);
    createEReference(statementsEClass, STATEMENTS__QRYADDITIONAL);

    aggregateStatementsEClass = createEClass(AGGREGATE_STATEMENTS);
    createEAttribute(aggregateStatementsEClass, AGGREGATE_STATEMENTS__OP_AGG);
    createEAttribute(aggregateStatementsEClass, AGGREGATE_STATEMENTS__AGG_FIELD);

    getStatementsEClass = createEClass(GET_STATEMENTS);
    createEAttribute(getStatementsEClass, GET_STATEMENTS__OP_GET);

    additionalQueryEClass = createEClass(ADDITIONAL_QUERY);
    createEAttribute(additionalQueryEClass, ADDITIONAL_QUERY__CONNECTOR);
    createEAttribute(additionalQueryEClass, ADDITIONAL_QUERY__Q2KEY);
    createEReference(additionalQueryEClass, ADDITIONAL_QUERY__Q2VAL);

    inputValEClass = createEClass(INPUT_VAL);

    intLiteralEClass = createEClass(INT_LITERAL);
    createEAttribute(intLiteralEClass, INT_LITERAL__VALUE);

    stringLiteralEClass = createEClass(STRING_LITERAL);
    createEAttribute(stringLiteralEClass, STRING_LITERAL__VALUE);

    // Create enums
    connectorEEnum = createEEnum(CONNECTOR);
    operationAggEEnum = createEEnum(OPERATION_AGG);
    operationGETEEnum = createEEnum(OPERATION_GET);
    inputFieldSingleEEnum = createEEnum(INPUT_FIELD_SINGLE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    aggregateStatementsEClass.getESuperTypes().add(this.getStatements());
    getStatementsEClass.getESuperTypes().add(this.getStatements());
    stringLiteralEClass.getESuperTypes().add(this.getInputVal());

    // Initialize classes and features; add operations and parameters
    initEClass(jsonQueryModelEClass, JSONQueryModel.class, "JSONQueryModel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getJSONQueryModel_InputStatement(), this.getStatements(), null, "inputStatement", null, 0, -1, JSONQueryModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(statementsEClass, Statements.class, "Statements", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStatements_Q1key(), this.getInputFieldSingle(), "q1key", null, 0, 1, Statements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getStatements_Q1val(), this.getInputVal(), null, "q1val", null, 0, 1, Statements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getStatements_Qryadditional(), this.getAdditionalQuery(), null, "qryadditional", null, 0, 1, Statements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(aggregateStatementsEClass, AggregateStatements.class, "AggregateStatements", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAggregateStatements_OpAgg(), this.getOperationAgg(), "opAgg", null, 0, 1, AggregateStatements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAggregateStatements_AggField(), this.getInputFieldSingle(), "aggField", null, 0, 1, AggregateStatements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(getStatementsEClass, GetStatements.class, "GetStatements", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGetStatements_OpGet(), this.getOperationGET(), "opGet", null, 0, 1, GetStatements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(additionalQueryEClass, AdditionalQuery.class, "AdditionalQuery", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAdditionalQuery_Connector(), this.getConnector(), "connector", null, 0, 1, AdditionalQuery.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAdditionalQuery_Q2key(), this.getInputFieldSingle(), "q2key", null, 0, 1, AdditionalQuery.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAdditionalQuery_Q2val(), this.getInputVal(), null, "q2val", null, 0, 1, AdditionalQuery.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(inputValEClass, InputVal.class, "InputVal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(intLiteralEClass, INTLiteral.class, "INTLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getINTLiteral_Value(), ecorePackage.getEInt(), "value", null, 0, 1, INTLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stringLiteralEClass, StringLiteral.class, "StringLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStringLiteral_Value(), ecorePackage.getEString(), "value", null, 0, 1, StringLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(connectorEEnum, Connector.class, "Connector");
    addEEnumLiteral(connectorEEnum, Connector.AND);
    addEEnumLiteral(connectorEEnum, Connector.OR);

    initEEnum(operationAggEEnum, OperationAgg.class, "OperationAgg");
    addEEnumLiteral(operationAggEEnum, OperationAgg.AVG);

    initEEnum(operationGETEEnum, OperationGET.class, "OperationGET");
    addEEnumLiteral(operationGETEEnum, OperationGET.DATA);
    addEEnumLiteral(operationGETEEnum, OperationGET.COUNT);

    initEEnum(inputFieldSingleEEnum, InputFieldSingle.class, "InputFieldSingle");
    addEEnumLiteral(inputFieldSingleEEnum, InputFieldSingle.FIRST_NAME);
    addEEnumLiteral(inputFieldSingleEEnum, InputFieldSingle.LAST_NAME);
    addEEnumLiteral(inputFieldSingleEEnum, InputFieldSingle.GENDER);
    addEEnumLiteral(inputFieldSingleEEnum, InputFieldSingle.COUNRTY_CODE);
    addEEnumLiteral(inputFieldSingleEEnum, InputFieldSingle.CITY_NAME);
    addEEnumLiteral(inputFieldSingleEEnum, InputFieldSingle.IS_VACCINATED);
    addEEnumLiteral(inputFieldSingleEEnum, InputFieldSingle.INCOME);

    // Create resource
    createResource(eNS_URI);
  }

} //JsonQPackageImpl
