/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.jsonQ.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import uk.ac.kcl.course.jsonQ.InputFieldSingle;
import uk.ac.kcl.course.jsonQ.InputVal;
import uk.ac.kcl.course.jsonQ.JsonQPackage;
import uk.ac.kcl.course.jsonQ.Operation;
import uk.ac.kcl.course.jsonQ.Statements;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Statements</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.course.jsonQ.impl.StatementsImpl#getOperation <em>Operation</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.impl.StatementsImpl#getQ1key <em>Q1key</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.impl.StatementsImpl#getQ1val <em>Q1val</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.impl.StatementsImpl#getConnector <em>Connector</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.impl.StatementsImpl#getQ2key <em>Q2key</em>}</li>
 *   <li>{@link uk.ac.kcl.course.jsonQ.impl.StatementsImpl#getQ2val <em>Q2val</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StatementsImpl extends MinimalEObjectImpl.Container implements Statements
{
  /**
   * The default value of the '{@link #getOperation() <em>Operation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperation()
   * @generated
   * @ordered
   */
  protected static final Operation OPERATION_EDEFAULT = Operation.DATA;

  /**
   * The cached value of the '{@link #getOperation() <em>Operation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperation()
   * @generated
   * @ordered
   */
  protected Operation operation = OPERATION_EDEFAULT;

  /**
   * The default value of the '{@link #getQ1key() <em>Q1key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQ1key()
   * @generated
   * @ordered
   */
  protected static final InputFieldSingle Q1KEY_EDEFAULT = InputFieldSingle.AREA_TYPE;

  /**
   * The cached value of the '{@link #getQ1key() <em>Q1key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQ1key()
   * @generated
   * @ordered
   */
  protected InputFieldSingle q1key = Q1KEY_EDEFAULT;

  /**
   * The cached value of the '{@link #getQ1val() <em>Q1val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQ1val()
   * @generated
   * @ordered
   */
  protected InputVal q1val;

  /**
   * The cached value of the '{@link #getConnector() <em>Connector</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConnector()
   * @generated
   * @ordered
   */
  protected EList<String> connector;

  /**
   * The default value of the '{@link #getQ2key() <em>Q2key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQ2key()
   * @generated
   * @ordered
   */
  protected static final InputFieldSingle Q2KEY_EDEFAULT = InputFieldSingle.AREA_TYPE;

  /**
   * The cached value of the '{@link #getQ2key() <em>Q2key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQ2key()
   * @generated
   * @ordered
   */
  protected InputFieldSingle q2key = Q2KEY_EDEFAULT;

  /**
   * The cached value of the '{@link #getQ2val() <em>Q2val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQ2val()
   * @generated
   * @ordered
   */
  protected InputVal q2val;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StatementsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JsonQPackage.Literals.STATEMENTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operation getOperation()
  {
    return operation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperation(Operation newOperation)
  {
    Operation oldOperation = operation;
    operation = newOperation == null ? OPERATION_EDEFAULT : newOperation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonQPackage.STATEMENTS__OPERATION, oldOperation, operation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InputFieldSingle getQ1key()
  {
    return q1key;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQ1key(InputFieldSingle newQ1key)
  {
    InputFieldSingle oldQ1key = q1key;
    q1key = newQ1key == null ? Q1KEY_EDEFAULT : newQ1key;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonQPackage.STATEMENTS__Q1KEY, oldQ1key, q1key));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InputVal getQ1val()
  {
    return q1val;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetQ1val(InputVal newQ1val, NotificationChain msgs)
  {
    InputVal oldQ1val = q1val;
    q1val = newQ1val;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JsonQPackage.STATEMENTS__Q1VAL, oldQ1val, newQ1val);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQ1val(InputVal newQ1val)
  {
    if (newQ1val != q1val)
    {
      NotificationChain msgs = null;
      if (q1val != null)
        msgs = ((InternalEObject)q1val).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JsonQPackage.STATEMENTS__Q1VAL, null, msgs);
      if (newQ1val != null)
        msgs = ((InternalEObject)newQ1val).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JsonQPackage.STATEMENTS__Q1VAL, null, msgs);
      msgs = basicSetQ1val(newQ1val, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonQPackage.STATEMENTS__Q1VAL, newQ1val, newQ1val));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getConnector()
  {
    if (connector == null)
    {
      connector = new EDataTypeEList<String>(String.class, this, JsonQPackage.STATEMENTS__CONNECTOR);
    }
    return connector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InputFieldSingle getQ2key()
  {
    return q2key;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQ2key(InputFieldSingle newQ2key)
  {
    InputFieldSingle oldQ2key = q2key;
    q2key = newQ2key == null ? Q2KEY_EDEFAULT : newQ2key;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonQPackage.STATEMENTS__Q2KEY, oldQ2key, q2key));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InputVal getQ2val()
  {
    return q2val;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetQ2val(InputVal newQ2val, NotificationChain msgs)
  {
    InputVal oldQ2val = q2val;
    q2val = newQ2val;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JsonQPackage.STATEMENTS__Q2VAL, oldQ2val, newQ2val);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQ2val(InputVal newQ2val)
  {
    if (newQ2val != q2val)
    {
      NotificationChain msgs = null;
      if (q2val != null)
        msgs = ((InternalEObject)q2val).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JsonQPackage.STATEMENTS__Q2VAL, null, msgs);
      if (newQ2val != null)
        msgs = ((InternalEObject)newQ2val).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JsonQPackage.STATEMENTS__Q2VAL, null, msgs);
      msgs = basicSetQ2val(newQ2val, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JsonQPackage.STATEMENTS__Q2VAL, newQ2val, newQ2val));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JsonQPackage.STATEMENTS__Q1VAL:
        return basicSetQ1val(null, msgs);
      case JsonQPackage.STATEMENTS__Q2VAL:
        return basicSetQ2val(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JsonQPackage.STATEMENTS__OPERATION:
        return getOperation();
      case JsonQPackage.STATEMENTS__Q1KEY:
        return getQ1key();
      case JsonQPackage.STATEMENTS__Q1VAL:
        return getQ1val();
      case JsonQPackage.STATEMENTS__CONNECTOR:
        return getConnector();
      case JsonQPackage.STATEMENTS__Q2KEY:
        return getQ2key();
      case JsonQPackage.STATEMENTS__Q2VAL:
        return getQ2val();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JsonQPackage.STATEMENTS__OPERATION:
        setOperation((Operation)newValue);
        return;
      case JsonQPackage.STATEMENTS__Q1KEY:
        setQ1key((InputFieldSingle)newValue);
        return;
      case JsonQPackage.STATEMENTS__Q1VAL:
        setQ1val((InputVal)newValue);
        return;
      case JsonQPackage.STATEMENTS__CONNECTOR:
        getConnector().clear();
        getConnector().addAll((Collection<? extends String>)newValue);
        return;
      case JsonQPackage.STATEMENTS__Q2KEY:
        setQ2key((InputFieldSingle)newValue);
        return;
      case JsonQPackage.STATEMENTS__Q2VAL:
        setQ2val((InputVal)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JsonQPackage.STATEMENTS__OPERATION:
        setOperation(OPERATION_EDEFAULT);
        return;
      case JsonQPackage.STATEMENTS__Q1KEY:
        setQ1key(Q1KEY_EDEFAULT);
        return;
      case JsonQPackage.STATEMENTS__Q1VAL:
        setQ1val((InputVal)null);
        return;
      case JsonQPackage.STATEMENTS__CONNECTOR:
        getConnector().clear();
        return;
      case JsonQPackage.STATEMENTS__Q2KEY:
        setQ2key(Q2KEY_EDEFAULT);
        return;
      case JsonQPackage.STATEMENTS__Q2VAL:
        setQ2val((InputVal)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JsonQPackage.STATEMENTS__OPERATION:
        return operation != OPERATION_EDEFAULT;
      case JsonQPackage.STATEMENTS__Q1KEY:
        return q1key != Q1KEY_EDEFAULT;
      case JsonQPackage.STATEMENTS__Q1VAL:
        return q1val != null;
      case JsonQPackage.STATEMENTS__CONNECTOR:
        return connector != null && !connector.isEmpty();
      case JsonQPackage.STATEMENTS__Q2KEY:
        return q2key != Q2KEY_EDEFAULT;
      case JsonQPackage.STATEMENTS__Q2VAL:
        return q2val != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (operation: ");
    result.append(operation);
    result.append(", q1key: ");
    result.append(q1key);
    result.append(", connector: ");
    result.append(connector);
    result.append(", q2key: ");
    result.append(q2key);
    result.append(')');
    return result.toString();
  }

} //StatementsImpl
