/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JsonQStandaloneSetup extends JsonQStandaloneSetupGenerated {

	public static void doSetup() {
		new JsonQStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
