/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JsonQRuntimeModule extends AbstractJsonQRuntimeModule {
}
