/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.course.JsonQRuntimeModule;
import uk.ac.kcl.course.JsonQStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JsonQIdeSetup extends JsonQStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JsonQRuntimeModule(), new JsonQIdeModule()));
	}
	
}
