/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.course.parser.antlr.internal.InternalJsonQParser;
import uk.ac.kcl.course.services.JsonQGrammarAccess;

public class JsonQParser extends AbstractAntlrParser {

	@Inject
	private JsonQGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJsonQParser createParser(XtextTokenStream stream) {
		return new InternalJsonQParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "JSONQueryModel";
	}

	public JsonQGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JsonQGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
