/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.course.JsonDSL.ui.internal.JsonDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JsonQExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(JsonDSLActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		JsonDSLActivator activator = JsonDSLActivator.getInstance();
		return activator != null ? activator.getInjector(JsonDSLActivator.UK_AC_KCL_COURSE_JSONQ) : null;
	}

}
