/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JsonQUiModule extends AbstractJsonQUiModule {

	public JsonQUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
