/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import uk.ac.kcl.course.jsonQ.INTLiteral;
import uk.ac.kcl.course.jsonQ.JSONQueryModel;
import uk.ac.kcl.course.jsonQ.JsonQPackage;
import uk.ac.kcl.course.jsonQ.Statements;
import uk.ac.kcl.course.jsonQ.StringLiteral;
import uk.ac.kcl.course.services.JsonQGrammarAccess;

@SuppressWarnings("all")
public class JsonQSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private JsonQGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == JsonQPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case JsonQPackage.INT_LITERAL:
				sequence_INTLiteral(context, (INTLiteral) semanticObject); 
				return; 
			case JsonQPackage.JSON_QUERY_MODEL:
				sequence_JSONQueryModel(context, (JSONQueryModel) semanticObject); 
				return; 
			case JsonQPackage.STATEMENTS:
				sequence_Statements(context, (Statements) semanticObject); 
				return; 
			case JsonQPackage.STRING_LITERAL:
				sequence_StringLiteral(context, (StringLiteral) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     InputVal returns INTLiteral
	 *     INTLiteral returns INTLiteral
	 *
	 * Constraint:
	 *     value=INT
	 */
	protected void sequence_INTLiteral(ISerializationContext context, INTLiteral semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JsonQPackage.Literals.INT_LITERAL__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JsonQPackage.Literals.INT_LITERAL__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getINTLiteralAccess().getValueINTTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     JSONQueryModel returns JSONQueryModel
	 *
	 * Constraint:
	 *     inputStatement+=Statements+
	 */
	protected void sequence_JSONQueryModel(ISerializationContext context, JSONQueryModel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Statements returns Statements
	 *
	 * Constraint:
	 *     (operation=Operation q1key=InputFieldSingle q1val=InputVal (connector+='AND' | connector+='OR')? (q2key=InputFieldSingle q2val=InputVal)?)
	 */
	protected void sequence_Statements(ISerializationContext context, Statements semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     InputVal returns StringLiteral
	 *     StringLiteral returns StringLiteral
	 *
	 * Constraint:
	 *     value=STRING
	 */
	protected void sequence_StringLiteral(ISerializationContext context, StringLiteral semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JsonQPackage.Literals.STRING_LITERAL__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JsonQPackage.Literals.STRING_LITERAL__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStringLiteralAccess().getValueSTRINGTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
}
