/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.course.scoping;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import uk.ac.kcl.course.jsonQ.AggregateStatements;

/**
 * This class contains custom scoping description.
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class JsonQScopeProvider extends AbstractDeclarativeScopeProvider {
  public IScope scope_AggregateStatements_aggField(final AggregateStatements context, final EReference ref) {
    return null;
  }
}
